services:  
  postgres16:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_USERPASSWORD}
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE}
    depends_on:
      - postgres16
    entrypoint: [ "/app/wait-for.sh", "postgres16:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
    