name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: ci-test-environment
    services:
      postgres16:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ${{ vars.DB_USERPASSWORD }}
          POSTGRES_USER: ${{ vars.DB_USERNAME }}
          POSTGRES_DB: simple_bank
          POSTGRES_PORT: 5432
          POSTGRES_HOST: postgres16
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.21'

    - name: Install migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Migrate up
      run: make migrateup
      env:
        DB_SOURCE: ${{ vars.DB_SOURCE }}
        POSTGRES_HOST: postgres16
        POSTGRES_PORT: 5432

    - name: Test
      run: make test
      env:
        DB_DRIVER: ${{ vars.DB_DRIVER }}
        DB_SOURCE: ${{ vars.DB_SOURCE }}
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_USERPASSWORD: ${{ vars.DB_USERPASSWORD }}
        SERVER_ADDRESS: ${{ vars.SERVER_ADDRESS }}